version: '3'

services:
    nginx:
        build:
            context: ./nginx/client
            dockerfile: Dockerfile
        volumes:
            - build_app:/var/www

    frontend:
        build: ./client
        container_name: frontend
        command: sh -c "npm run build && cp -R build/* /var/www"
        volumes:
            - build_app:/var/www

volumes:
    build_app:
