version: '3'

services:
    nginx:
        build: 
            context: ./nginx
            dockerfile: Dockerfile
        container_name: nginx
        ports:
            - 80:80
            - 8000:8000
        restart: "on-failure"
