# Generated by Django 3.2 on 2021-05-01 22:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_COD_96_removing_model_menu_and_redoing_everything'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='deliveryAddress',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cart', to='core.deliveryaddress'),
        ),
    ]
