# Generated by Django 3.2 on 2021-05-01 22:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_cart_deliveryaddress'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='total',
        ),
    ]
