# Generated by Django 3.2.3 on 2021-05-28 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_orderitem_total'),
    ]

    operations = [
        migrations.CreateModel(
            name='TagFoodItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updateAt', models.DateTimeField(auto_created=True, auto_now=True)),
                ('createAt', models.DateTimeField(auto_created=True, auto_now_add=True)),
                ('name', models.CharField(max_length=20)),
                ('description', models.TextField(blank=True, max_length=250, null=True)),
                ('color', models.CharField(blank=True, choices=[('#ff0000', 'Red'), ('#007fff', 'Blue'), ('#9edeff', 'Light Blue'), ('#3ff8ff', 'Purple'), ('#3fffaf', 'Light Green'), ('#00e070', 'Gree'), ('#fff200', 'Yellow'), ('#ff9900', 'Orange')], max_length=15, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='fooditem',
            name='ingredients',
            field=models.TextField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='fooditem',
            name='description',
            field=models.TextField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='fooditem',
            name='tags',
            field=models.ManyToManyField(blank=True, null=True, related_name='foodItems', to='core.TagFoodItem'),
        ),
    ]
