# Generated by Django 3.2.3 on 2021-05-28 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20210528_0131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tagfooditem',
            name='color',
            field=models.CharField(blank=True, choices=[('#ff0000', 'Red'), ('#007fff', 'Blue'), ('#9edeff', 'Light Blue'), ('#3ff8ff', 'Purple'), ('#3fffaf', 'Light Green'), ('#00e070', 'Gree'), ('#fff200', 'Yellow'), ('#ff9900', 'Orange')], default='#007fff', max_length=15, null=True),
        ),
    ]
