# Generated by Django 3.2.3 on 2021-05-29 15:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_tagfooditem_color'),
    ]

    operations = [
        migrations.CreateModel(
            name='IngredientItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updateAt', models.DateTimeField(auto_created=True, auto_now=True)),
                ('createAt', models.DateTimeField(auto_created=True, auto_now_add=True)),
                ('name', models.CharField(max_length=50)),
                ('details', models.TextField(blank=True, max_length=250, null=True)),
                ('FoodItem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='IngredientItems', to='core.fooditem')),
            ],
        ),
    ]
