# Generated by Django 3.2.3 on 2021-05-29 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_orderitem_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fooditem',
            name='ingredients',
        ),
    ]
