# Generated by Django 3.2.3 on 2021-05-29 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_remove_fooditem_ingredients'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ingredientitem',
            old_name='FoodItem',
            new_name='foodItem',
        ),
    ]
