# Generated by Django 3.2.3 on 2021-05-30 15:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_rename_fooditem_ingredientitem_fooditem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredientitem',
            name='foodItem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredientItems', to='core.fooditem'),
        ),
    ]
