# Generated by Django 3.2.3 on 2021-06-02 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_ingredientitem_fooditem'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredientitem',
            name='selected',
            field=models.BooleanField(default=False),
        ),
    ]
