# Generated by Django 3.2.3 on 2021-06-04 01:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_ingredientitem_selected'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredientitem',
            name='foodItem',
        ),
        migrations.CreateModel(
            name='IngredientChosenToFoodItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updateAt', models.DateTimeField(auto_created=True, auto_now=True)),
                ('createAt', models.DateTimeField(auto_created=True, auto_now_add=True)),
                ('foodItem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.fooditem')),
                ('ingredientItem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.ingredientitem')),
            ],
        ),
        migrations.AddField(
            model_name='fooditem',
            name='ingredients',
            field=models.ManyToManyField(through='core.IngredientChosenToFoodItem', to='core.IngredientItem'),
        ),
    ]
