# Generated by Django 3.2.3 on 2021-06-05 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20210604_0138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fooditem',
            name='ingredients',
            field=models.ManyToManyField(null=True, through='core.IngredientChosenToFoodItem', to='core.IngredientItem'),
        ),
    ]
