# Generated by Django 3.2.3 on 2021-06-08 12:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_fooditem_ingredients'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredientitem',
            name='virtualshop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ingredients', to='core.virtualshop'),
        ),
    ]
