# Generated by Django 3.2.3 on 2021-06-08 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_ingredientitem_virtualshop'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fooditem',
            name='ingredients',
            field=models.ManyToManyField(related_name='foodItems', through='core.IngredientChosenToFoodItem', to='core.IngredientItem'),
        ),
    ]
