# Generated by Django 3.2.3 on 2021-06-09 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_alter_fooditem_ingredients'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredientitem',
            name='customizable',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ingredientitem',
            name='extra_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True),
        ),
    ]
