# Generated by Django 3.2.5 on 2021-07-10 23:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_auto_20210630_1356'),
    ]

    operations = [
        migrations.AddField(
            model_name='fooditem',
            name='virtualShop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='foodItems', to='core.virtualshop'),
        ),
    ]
