# Generated by Django 3.2.5 on 2021-07-10 23:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_fooditem_virtualshop'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fooditem',
            name='virtualShop',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='foodItems', to='core.virtualshop'),
        ),
    ]
